project_name: yylint
before:
  hooks:
    - go mod tidy
builds:
  -
    main: ./cmd/yylint/main.go
    binary: yylint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - windows
      - darwin
    goarch:
      - amd64
archives:
  -
    wrap_in_directory: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: true
  prerelease: auto
